### ISSUE TITLE
Help title incorrect

### ISSUE THREAD

**Issue by akruphi** [VPROFi/sqlplugin#2]
In help in plugin lists by **Shift-F2** this plugin show as **Panel for configuring network interfaces and routes**:
![изображение](https://github.com/VPROFi/sqlplugin/assets/92621645/76f44c1e-cb0f-4a12-83f3-6c004b4e2473)
Please rename to **Panel SQL**.

**Comment by VPROFi** [comment]
[fix incorrect eng header](https://github.com/VPROFi/sqlplugin/commit/c855546abcd3e08044ebb4af5dead436e740f0f0)
